---
name: CI

on:
  push:
    branches: [ "master" ]

  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - name: install deps
      run: sudo apt-get install -y libboost-all-dev libjsoncpp-dev antlr3 libantlr3c-dev minisat clang llvm

    - name: configure
      run: ./setup.sh

    - name: compile
      run: make -j $(nproc)

    - name: functional tests
      run: YASMV_HOME=$(pwd) make test
